server:
  port: 8761
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6001/eureka
  instance:
    prefer-ip-address: true #以ip注册到注册中心
spring:
  application:
    name: spring-cloud-config-server
  profiles:
    active: native #本地配置
  cloud:
    config:
      server:
        native:  #本地配置
          search-locations: E:/opensource/git/aigou-config
#        git:
#          uri: https://github.com/solargen/aigou-config.git
#          username: solargen
#          password: itsource0814

